#!/bin/bash
set -eu

prefix="$PWD/deps"
mkdir "$prefix"
mkdir "$prefix/src"
cd "$prefix/src"

# liberfa
erfa_version="2.0.1"
erfa_tarball="erfa-${erfa_version}.tar.xz"
curl -LO "https://github.com/liberfa/erfa/releases/download/v${erfa_version}/${erfa_tarball}"
tar -xaf "$erfa_tarball"
cd "erfa-${erfa_version}"
[[ -f ./configure ]] || ./bootstrap.sh
./configure --prefix="$prefix" --disable-shared
make install
