name: ci

on:
  push:
    branches: master

env:
  TAG: gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ github.event.repository.name }}:latest

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_JSON_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Configure docker to use gcloud for authentication
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build docker image
        run: |-
          docker build --tag "$TAG" .

      - name: Publish image to GCR
        run: |-
          docker push "$TAG"

