name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create package name, tagged by date
        run: echo "ghp_pkg=docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build docker image
        run: docker build --build-arg SSH_PRIVATE_KEY="${{ secrets.GH_READ_ACCESS_SSH_KEY_ED25519 }}" --tag "${{ env.ghp_pkg }}" .

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin

      - name: Publish image to GitHub Packages
        run: docker push "${{ env.ghp_pkg }}"
