name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      package_name: "${{ github.event.repository.name }}/${{ github.event.repository.name }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create package name, tagged by date
        run: echo "ghp_pkg=ghcr.io/ccatobs/${{ env.package_name }}:$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build docker image
        run: docker build --build-arg SSH_PRIVATE_KEY="${{ secrets.GH_READ_ACCESS_SSH_KEY_ED25519 }}" --tag "${{ env.ghp_pkg }}" .

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image to GitHub Packages
        run: docker push "${{ env.ghp_pkg }}"

      - name: Delete untagged packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: "${{ env.package_name }}"
          package-type: container
          min-versions-to-keep: 0
          delete-only-untagged-versions: true

      - name: Delete old packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: "${{ env.package_name }}"
          package-type: container
          min-versions-to-keep: 10
